import React from 'react';
import {
  Composition, useCurrentFrame, Img, staticFile,
  AbsoluteFill, Sequence, OffthreadVideo, interpolate,
} from 'remotion';
import { getVideoMetadata } from '@remotion/media-utils';

// Generic BEIA reel: renders a vertical (1080x1920) reel from a list of card
// image URLs. Brand look (end-card name + accent colour) comes in as props so
// the one composition serves every brand — values supplied by beia_core from
// brand config at render time. Nothing here is brand-specific.

const CARD_DURATION = 150; // 5s @ 30fps
const FADE_DURATION = 20;

type ReelProps = {
  images: string[];
  brandName?: string;
  accentColor?: string;
};

const QuoteVideo: React.FC<ReelProps> = ({
  images,
  brandName = 'BEIA',
  accentColor = '#F97316',
}) => {
  const frame = useCurrentFrame();
  const totalFrames = images.length * CARD_DURATION;
  const currentCardIndex = Math.floor(frame / CARD_DURATION);
  const frameInCard = frame % CARD_DURATION;

  let opacity = 1;
  if (frameInCard < FADE_DURATION) {
    opacity = frameInCard / FADE_DURATION;
  } else if (frameInCard > CARD_DURATION - FADE_DURATION) {
    opacity = (CARD_DURATION - frameInCard) / FADE_DURATION;
  }

  const scale = 1 + (frameInCard / CARD_DURATION) * 0.02;
  const progress = frame / totalFrames;

  if (currentCardIndex >= images.length) {
    return (
      <AbsoluteFill style={{ backgroundColor: '#FFFFFF' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%' }}>
          <p style={{ fontSize: 24, color: '#333' }}>{brandName}</p>
        </div>
      </AbsoluteFill>
    );
  }

  return (
    <AbsoluteFill style={{ backgroundColor: '#FFFFFF' }}>
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
        opacity,
        transform: `scale(${scale})`,
      }}>
        <Img
          src={images[currentCardIndex].startsWith('http') ? images[currentCardIndex] : staticFile(images[currentCardIndex])}
          style={{ width: '100%', height: '100%', objectFit: 'contain' }}
        />
      </div>
      <div style={{
        position: 'absolute',
        bottom: 40,
        left: 40,
        right: 40,
        height: 4,
        backgroundColor: 'rgba(0,0,0,0.1)',
        borderRadius: 2,
      }}>
        <div style={{
          width: `${progress * 100}%`,
          height: '100%',
          backgroundColor: accentColor,
          borderRadius: 2,
        }} />
      </div>
    </AbsoluteFill>
  );
};

const DEFAULT_IMAGES = [
  'quotes/quote1.png',
  'quotes/quote2.png',
  'quotes/quote3.png',
];

// ── HookIntroReel ────────────────────────────────────────────────────────────
// The Ruoth (and any brand's) repurpose short: a ~3s white card with the hook
// typed in (typewriter), then the base campaign video cuts in. GENERIC — the hook
// text, the base video URL and the brand accent all come in as props from
// beia_core (the hook is generated by the scheduler; the base mp4 is the brand's
// asset). Nothing here is brand-specific.

const INTRO_FRAMES = 90; // 3s @ 30fps
const TYPE_FRAMES = 60;  // hook fully typed by 2s

type HookReelProps = {
  hook: string;
  videoUrl: string;
  brandName?: string;
  accentColor?: string;
};

const TypewriterHook: React.FC<{ hook: string; accentColor: string }> = ({ hook, accentColor }) => {
  const frame = useCurrentFrame();
  const chars = Math.floor(
    interpolate(frame, [0, TYPE_FRAMES], [0, hook.length], {
      extrapolateLeft: 'clamp',
      extrapolateRight: 'clamp',
    })
  );
  const shown = hook.slice(0, chars);
  const cursorOn = Math.floor(frame / 8) % 2 === 0;
  return (
    <AbsoluteFill
      style={{
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 90,
      }}
    >
      <p
        style={{
          fontSize: 76,
          fontWeight: 700,
          color: '#111111',
          textAlign: 'center',
          lineHeight: 1.2,
          fontFamily: 'Arial, Helvetica, sans-serif',
          margin: 0,
        }}
      >
        {shown}
        <span style={{ color: accentColor, opacity: cursorOn ? 1 : 0 }}>|</span>
      </p>
    </AbsoluteFill>
  );
};

const HookIntroReel: React.FC<HookReelProps> = ({
  hook,
  videoUrl,
  accentColor = '#C0392B',
}) => {
  return (
    <AbsoluteFill style={{ backgroundColor: '#FFFFFF' }}>
      <Sequence durationInFrames={INTRO_FRAMES}>
        <TypewriterHook hook={hook} accentColor={accentColor} />
      </Sequence>
      <Sequence from={INTRO_FRAMES}>
        <AbsoluteFill style={{ backgroundColor: '#000000' }}>
          <OffthreadVideo
            src={videoUrl}
            style={{ width: '100%', height: '100%', objectFit: 'contain' }}
          />
        </AbsoluteFill>
      </Sequence>
    </AbsoluteFill>
  );
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
    <Composition
      id="HookIntroReel"
      component={HookIntroReel}
      durationInFrames={INTRO_FRAMES + 300}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{
        hook: 'Still guessing this ingredient?',
        videoUrl: '',
        brandName: 'Ruoth',
        accentColor: '#C0392B',
      }}
      calculateMetadata={async ({ props }) => {
        const fps = 30;
        let vidFrames = 300; // 10s fallback if probing fails
        if (props.videoUrl) {
          try {
            const meta = await getVideoMetadata(props.videoUrl);
            vidFrames = Math.round(meta.durationInSeconds * fps);
          } catch (e) {
            // keep fallback — never fail the render on a probe error
          }
        }
        return { durationInFrames: INTRO_FRAMES + Math.max(1, vidFrames), fps };
      }}
    />
    <Composition
      id="QuoteReel"
      component={QuoteVideo}
      durationInFrames={DEFAULT_IMAGES.length * CARD_DURATION}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{ images: DEFAULT_IMAGES, brandName: 'BEIA', accentColor: '#F97316' }}
      calculateMetadata={({ props }) => ({
        durationInFrames: Math.max(1, (props.images?.length || 1) * CARD_DURATION),
      })}
    />
    </>
  );
};
