import React from 'react';
import {
  Composition, useCurrentFrame, Img, staticFile,
  AbsoluteFill, Sequence, OffthreadVideo, Audio, interpolate,
} from 'remotion';
import { getVideoMetadata } from '@remotion/media-utils';

// Generic BEIA reel: renders a vertical (1080x1920) reel from a list of card
// image URLs. Brand look (end-card name + accent colour) comes in as props so
// the one composition serves every brand — values supplied by beia_core from
// brand config at render time. Nothing here is brand-specific.

const CARD_DURATION = 150; // 5s @ 30fps
const FADE_DURATION = 20;

// Remote media fetched DURING a render is a single point of failure: the music
// host intermittently times out from CI runners and Remotion treats a failed
// <Audio> fetch as fatal, killing an otherwise-finished video. So CI downloads
// the track first and passes a bare filename; anything without a scheme is
// resolved out of public/ and never leaves the runner. Absolute URLs still work
// for callers that want them.
const resolveMedia = (src?: string): string | undefined => {
  if (!src) return undefined;
  return /^https?:\/\//i.test(src) ? src : staticFile(src);
};

type ReelProps = {
  images: string[];
  brandName?: string;
  accentColor?: string;
};

const QuoteVideo: React.FC<ReelProps> = ({
  images,
  brandName = 'BEIA',
  accentColor = '#F97316',
}) => {
  const frame = useCurrentFrame();
  const totalFrames = images.length * CARD_DURATION;
  const currentCardIndex = Math.floor(frame / CARD_DURATION);
  const frameInCard = frame % CARD_DURATION;

  let opacity = 1;
  if (frameInCard < FADE_DURATION) {
    opacity = frameInCard / FADE_DURATION;
  } else if (frameInCard > CARD_DURATION - FADE_DURATION) {
    opacity = (CARD_DURATION - frameInCard) / FADE_DURATION;
  }

  const scale = 1 + (frameInCard / CARD_DURATION) * 0.02;
  const progress = frame / totalFrames;

  if (currentCardIndex >= images.length) {
    return (
      <AbsoluteFill style={{ backgroundColor: '#FFFFFF' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%' }}>
          <p style={{ fontSize: 24, color: '#333' }}>{brandName}</p>
        </div>
      </AbsoluteFill>
    );
  }

  return (
    <AbsoluteFill style={{ backgroundColor: '#FFFFFF' }}>
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
        opacity,
        transform: `scale(${scale})`,
      }}>
        <Img
          src={images[currentCardIndex].startsWith('http') ? images[currentCardIndex] : staticFile(images[currentCardIndex])}
          style={{ width: '100%', height: '100%', objectFit: 'contain' }}
        />
      </div>
      <div style={{
        position: 'absolute',
        bottom: 40,
        left: 40,
        right: 40,
        height: 4,
        backgroundColor: 'rgba(0,0,0,0.1)',
        borderRadius: 2,
      }}>
        <div style={{
          width: `${progress * 100}%`,
          height: '100%',
          backgroundColor: accentColor,
          borderRadius: 2,
        }} />
      </div>
    </AbsoluteFill>
  );
};

const DEFAULT_IMAGES = [
  'quotes/quote1.png',
  'quotes/quote2.png',
  'quotes/quote3.png',
];

// ── HookIntroReel ────────────────────────────────────────────────────────────
// The Ruoth (and any brand's) repurpose short: a ~3s white card with the hook
// typed in (typewriter), then the base campaign video cuts in. GENERIC — the hook
// text, the base video URL and the brand accent all come in as props from
// beia_core (the hook is generated by the scheduler; the base mp4 is the brand's
// asset). Nothing here is brand-specific.

const INTRO_FRAMES = 90; // 3s @ 30fps
const TYPE_FRAMES = 60;  // hook fully typed by 2s

type HookReelProps = {
  hook: string;
  videoUrl: string;
  brandName?: string;
  accentColor?: string;
  musicUrl?: string;     // royalty-free track baked over the whole reel (optional)
  musicVolume?: number;  // 0..1 (kept moderate so any clip audio still reads)
};

const TypewriterHook: React.FC<{ hook: string; accentColor: string }> = ({ hook, accentColor }) => {
  const frame = useCurrentFrame();
  const chars = Math.floor(
    interpolate(frame, [0, TYPE_FRAMES], [0, hook.length], {
      extrapolateLeft: 'clamp',
      extrapolateRight: 'clamp',
    })
  );
  const shown = hook.slice(0, chars);
  const cursorOn = Math.floor(frame / 8) % 2 === 0;
  return (
    <AbsoluteFill
      style={{
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 90,
      }}
    >
      <p
        style={{
          fontSize: 76,
          fontWeight: 700,
          color: '#111111',
          textAlign: 'center',
          lineHeight: 1.2,
          fontFamily: 'Arial, Helvetica, sans-serif',
          margin: 0,
        }}
      >
        {shown}
        <span style={{ color: accentColor, opacity: cursorOn ? 1 : 0 }}>|</span>
      </p>
    </AbsoluteFill>
  );
};

const HookIntroReel: React.FC<HookReelProps> = ({
  hook,
  videoUrl,
  accentColor = '#C0392B',
  musicUrl,
  musicVolume = 0.4,
}) => {
  return (
    <AbsoluteFill style={{ backgroundColor: '#FFFFFF' }}>
      {musicUrl ? <Audio src={resolveMedia(musicUrl)!} volume={musicVolume} loop /> : null}
      <Sequence durationInFrames={INTRO_FRAMES}>
        <TypewriterHook hook={hook} accentColor={accentColor} />
      </Sequence>
      <Sequence from={INTRO_FRAMES}>
        <AbsoluteFill style={{ backgroundColor: '#000000' }}>
          <OffthreadVideo
            src={videoUrl}
            style={{ width: '100%', height: '100%', objectFit: 'contain' }}
          />
        </AbsoluteFill>
      </Sequence>
    </AbsoluteFill>
  );
};

// ── HookImageReel ────────────────────────────────────────────────────────────
// The STILL-media sibling of HookIntroReel. Legacy campaigns (Ruoth's Launch
// Campaign) hold .jpg pins rather than .mp4 clips, so they can never satisfy a
// video-source composition — but they are still perfectly repurposable: the
// operator used to turn those stills into Shorts by hand. Same typed hook
// intro, then the still held with a slow Ken Burns push so it reads as motion.
// GENERIC — brand strings are props.

type HookImageReelProps = {
  hook: string;
  imageUrl: string;
  brandName?: string;
  accentColor?: string;
  musicUrl?: string;
  musicVolume?: number;
  holdSeconds?: number;
};

const IMAGE_HOLD_FRAMES = 240; // 8s @ 30fps

const HookImageReel: React.FC<HookImageReelProps> = ({
  hook,
  imageUrl,
  accentColor = '#C0392B',
  musicUrl,
  musicVolume = 0.4,
  holdSeconds,
}) => {
  const frame = useCurrentFrame();
  const hold = holdSeconds ? Math.round(holdSeconds * 30) : IMAGE_HOLD_FRAMES;
  const sinceImage = Math.max(0, frame - INTRO_FRAMES);
  // Slow push in — stills feel dead without movement on short-form.
  const scale = interpolate(sinceImage, [0, hold], [1, 1.08], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });

  return (
    <AbsoluteFill style={{ backgroundColor: '#FFFFFF' }}>
      {musicUrl ? <Audio src={resolveMedia(musicUrl)!} volume={musicVolume} loop /> : null}
      <Sequence durationInFrames={INTRO_FRAMES}>
        <TypewriterHook hook={hook} accentColor={accentColor} />
      </Sequence>
      <Sequence from={INTRO_FRAMES}>
        <AbsoluteFill
          style={{
            backgroundColor: '#000000',
            justifyContent: 'center',
            alignItems: 'center',
            overflow: 'hidden',
          }}
        >
          <Img
            src={imageUrl}
            style={{
              width: '100%',
              height: '100%',
              objectFit: 'contain',
              transform: `scale(${scale})`,
            }}
          />
        </AbsoluteFill>
      </Sequence>
    </AbsoluteFill>
  );
};

// ── TriviaReel ───────────────────────────────────────────────────────────────
// The CREATION surface (as opposed to HookIntroReel, which repurposes an
// existing clip). Manufactures a faceless trivia Short from text alone:
// branded intro -> question -> answer reveal -> CTA, narrated by a free
// CPU-only TTS voice with kinetic captions synced to it. GENERIC — every
// brand string comes in as a prop, so any brand reuses this composition.

type Caption = { text: string; startMs: number; endMs: number };

type TriviaReelProps = {
  question: string;
  answer: string;
  pillar?: string;
  narrationUrl?: string;   // absolute URL, else staticFile('narration.wav')
  captions?: Caption[];
  brandName?: string;
  accentColor?: string;
  logoUrl?: string;
  siteUrl?: string;
  musicUrl?: string;
  musicVolume?: number;
};

const TRIVIA_FPS = 30;
const TRIVIA_INTRO_FRAMES = 60;   // 2s branded intro
const TRIVIA_OUTRO_FRAMES = 60;   // 2s CTA end card

const KineticCaptions: React.FC<{ captions: Caption[]; accentColor: string }> = ({
  captions,
  accentColor,
}) => {
  const frame = useCurrentFrame();
  const ms = (frame / TRIVIA_FPS) * 1000;
  const active = captions.find((c) => ms >= c.startMs && ms <= c.endMs);
  if (!active) return null;

  // Pop in over the first 120ms of the caption.
  const since = ms - active.startMs;
  const scale = interpolate(since, [0, 120], [0.92, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });

  return (
    <AbsoluteFill
      style={{
        justifyContent: 'flex-end',
        alignItems: 'center',
        paddingBottom: 320,
      }}
    >
      <div
        style={{
          transform: `scale(${scale})`,
          maxWidth: '84%',
          textAlign: 'center',
          fontFamily: 'Arial, Helvetica, sans-serif',
          fontSize: 62,
          fontWeight: 700,
          lineHeight: 1.25,
          color: '#FFFFFF',
          textShadow: '0 4px 18px rgba(0,0,0,0.55)',
          background: 'rgba(0,0,0,0.42)',
          borderRadius: 24,
          padding: '18px 30px',
          borderBottom: `6px solid ${accentColor}`,
        }}
      >
        {active.text}
      </div>
    </AbsoluteFill>
  );
};

const TriviaReel: React.FC<TriviaReelProps> = ({
  question,
  answer,
  pillar = '',
  narrationUrl,
  captions = [],
  brandName = 'Ruoth',
  accentColor = '#C0392B',
  logoUrl,
  siteUrl = '',
  musicUrl,
  musicVolume = 0.16,
}) => {
  const frame = useCurrentFrame();
  const font = 'Arial, Helvetica, sans-serif';

  // The voice reads the on-screen question and answer verbatim, so captioning
  // those same lines double-prints them. Captions exist for narration that ADDS
  // something ("Think about it."), not to echo text already on screen.
  const norm = (s: string) =>
    (s || '').toLowerCase().replace(/[^a-z0-9]/g, '');
  const onScreen = new Set([norm(question), norm(answer)]);
  const spokenOnly = captions.filter((c) => !onScreen.has(norm(c.text)));

  // Answer reveals for the last third of the narrated body.
  const narrationFrames = captions.length
    ? Math.round((captions[captions.length - 1].endMs / 1000) * TRIVIA_FPS)
    : 8 * TRIVIA_FPS;
  const revealAt = TRIVIA_INTRO_FRAMES + Math.round(narrationFrames * 0.62);
  const revealed = frame >= revealAt;

  const audioSrc = narrationUrl || staticFile('narration.wav');

  return (
    <AbsoluteFill style={{ backgroundColor: '#0E0E0E' }}>
      {musicUrl ? <Audio src={resolveMedia(musicUrl)!} volume={musicVolume} loop /> : null}
      <Sequence from={TRIVIA_INTRO_FRAMES}>
        <Audio src={audioSrc} />
      </Sequence>

      {/* Branded intro */}
      <Sequence durationInFrames={TRIVIA_INTRO_FRAMES}>
        <AbsoluteFill
          style={{
            backgroundColor: '#FFFFFF',
            justifyContent: 'center',
            alignItems: 'center',
            padding: 80,
          }}
        >
          {logoUrl ? (
            <Img src={logoUrl} style={{ width: 260, marginBottom: 40 }} />
          ) : null}
          <div
            style={{
              fontFamily: font,
              fontSize: 60,
              fontWeight: 700,
              color: '#111111',
              textAlign: 'center',
              letterSpacing: 2,
            }}
          >
            {brandName.toUpperCase()} RECIPE TRIVIA
          </div>
          {pillar ? (
            <div
              style={{
                fontFamily: font,
                fontSize: 40,
                marginTop: 20,
                color: accentColor,
                fontWeight: 600,
              }}
            >
              {pillar}
            </div>
          ) : null}
        </AbsoluteFill>
      </Sequence>

      {/* Question + answer reveal, captions over the top */}
      <Sequence from={TRIVIA_INTRO_FRAMES}>
        <AbsoluteFill
          style={{ padding: 80, justifyContent: 'center', paddingBottom: 420 }}
        >
          <div
            style={{
              fontFamily: font,
              fontSize: 68,
              fontWeight: 700,
              color: '#FFFFFF',
              lineHeight: 1.3,
              textAlign: 'center',
            }}
          >
            {question}
          </div>
          {revealed ? (
            <div
              style={{
                fontFamily: font,
                fontSize: 58,
                fontWeight: 700,
                color: accentColor,
                textAlign: 'center',
                marginTop: 60,
                background: 'rgba(255,255,255,0.96)',
                borderRadius: 20,
                padding: '24px 30px',
              }}
            >
              {answer}
            </div>
          ) : null}
        </AbsoluteFill>
        <KineticCaptions captions={spokenOnly} accentColor={accentColor} />
      </Sequence>

      {/* CTA end card */}
      <Sequence from={TRIVIA_INTRO_FRAMES + narrationFrames}>
        <AbsoluteFill
          style={{
            backgroundColor: '#FFFFFF',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          {logoUrl ? (
            <Img src={logoUrl} style={{ width: 300, marginBottom: 36 }} />
          ) : null}
          <div style={{ fontFamily: font, fontSize: 52, color: accentColor, fontWeight: 700 }}>
            {siteUrl}
          </div>
        </AbsoluteFill>
      </Sequence>
    </AbsoluteFill>
  );
};

// ── OfferCard ────────────────────────────────────────────────────────────────
// The SELLING creative surface: a flexible product/offer card (still PNG) the
// design team can compose into any layout. GENERIC — every field comes in as a
// design spec prop authored by beia_core's creative worker (headline, price, CTA,
// product image, palette, layout). This is NOT the editorial quote card; it is a
// direct-response offer card. New layouts are added here without touching beia_core.

type OfferCardProps = {
  headline: string;
  subhead?: string;
  price?: string;        // pre-formatted, e.g. "£24" or "From £9/mo"
  cta?: string;          // e.g. "Shop now", "Start free"
  productImage?: string; // absolute URL of the real product shot (optional)
  brandName?: string;
  accentColor?: string;
  background?: string;   // card background when there is no full-bleed image
  textColor?: string;
  layout?: 'image_top' | 'overlay' | 'text_only';
};

const OfferCard: React.FC<OfferCardProps> = ({
  headline,
  subhead,
  price,
  cta = 'Shop now',
  productImage,
  brandName = 'BEIA',
  accentColor = '#C0392B',
  background = '#FFFFFF',
  textColor = '#111111',
  layout,
}) => {
  const resolved: OfferCardProps['layout'] =
    layout || (productImage ? 'image_top' : 'text_only');
  const font = 'Arial, Helvetica, sans-serif';

  const Brand = (
    <p style={{ margin: 0, fontSize: 30, fontWeight: 700, letterSpacing: 2,
      color: accentColor, fontFamily: font, textTransform: 'uppercase' }}>
      {brandName}
    </p>
  );
  const Price = price ? (
    <span style={{ display: 'inline-block', background: accentColor, color: '#FFFFFF',
      fontSize: 44, fontWeight: 700, padding: '10px 28px', borderRadius: 12,
      fontFamily: font }}>{price}</span>
  ) : null;
  const Cta = (
    <span style={{ display: 'inline-block', background: textColor, color: background,
      fontSize: 38, fontWeight: 700, padding: '18px 44px', borderRadius: 60,
      fontFamily: font }}>{cta} →</span>
  );

  if (resolved === 'overlay' && productImage) {
    return (
      <AbsoluteFill style={{ backgroundColor: '#000' }}>
        <Img src={productImage} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
        <AbsoluteFill style={{
          background: 'linear-gradient(to bottom, rgba(0,0,0,0.15) 30%, rgba(0,0,0,0.82) 100%)',
        }} />
        <AbsoluteFill style={{ padding: 80, justifyContent: 'space-between' }}>
          <div>{Brand}</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 28 }}>
            <p style={{ margin: 0, fontSize: 88, fontWeight: 700, lineHeight: 1.05,
              color: '#FFFFFF', fontFamily: font }}>{headline}</p>
            {subhead ? <p style={{ margin: 0, fontSize: 40, lineHeight: 1.25,
              color: 'rgba(255,255,255,0.92)', fontFamily: font }}>{subhead}</p> : null}
            <div style={{ display: 'flex', alignItems: 'center', gap: 28, marginTop: 8 }}>
              {Price}{Cta}
            </div>
          </div>
        </AbsoluteFill>
      </AbsoluteFill>
    );
  }

  if (resolved === 'image_top' && productImage) {
    return (
      <AbsoluteFill style={{ backgroundColor: background }}>
        <div style={{ height: '58%', width: '100%', backgroundColor: '#000' }}>
          <Img src={productImage} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
        </div>
        <div style={{ height: '42%', padding: 72, display: 'flex',
          flexDirection: 'column', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
            {Brand}
            <p style={{ margin: 0, fontSize: 66, fontWeight: 700, lineHeight: 1.08,
              color: textColor, fontFamily: font }}>{headline}</p>
            {subhead ? <p style={{ margin: 0, fontSize: 34, lineHeight: 1.25,
              color: 'rgba(17,17,17,0.7)', fontFamily: font }}>{subhead}</p> : null}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 24 }}>{Price}{Cta}</div>
        </div>
      </AbsoluteFill>
    );
  }

  // text_only — bold typographic offer card, no product shot
  return (
    <AbsoluteFill style={{ backgroundColor: background, padding: 90,
      justifyContent: 'space-between' }}>
      <div>{Brand}</div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
        <p style={{ margin: 0, fontSize: 96, fontWeight: 700, lineHeight: 1.04,
          color: textColor, fontFamily: font }}>{headline}</p>
        {subhead ? <p style={{ margin: 0, fontSize: 42, lineHeight: 1.25,
          color: 'rgba(17,17,17,0.7)', fontFamily: font }}>{subhead}</p> : null}
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 28 }}>{Price}{Cta}</div>
    </AbsoluteFill>
  );
};

// ── TriviaEpisode ────────────────────────────────────────────────────────────
// The retention rebuild of TriviaReel.
//
// TriviaReel narrated a statement: branded intro card, question, answer, end
// card. There was nothing to stay for, because the viewer was told a fact rather
// than given something to solve — and the first two seconds, which is the entire
// decision window, were spent on a logo.
//
// This composition renders a GAME laid out on a beat timeline:
//   hook       frame 0. No logo, no greeting. The challenge lands immediately.
//   challenge  what the viewer has to solve.
//   clue       progressive narrowing, 1-3 beats.
//   pressure   countdown — the moment before the answer.
//   reveal     the answer, visually unmistakable.
//   payoff     why it is correct. This is the beat that builds authority.
//   cta        one action, and only when a CTA type was assigned.
//
// Beat durations come from real measured narration, not estimates, so captions
// and reveals land on the voice. GENERIC: the mechanic decides the stage, so one
// composition serves every format, and every brand string arrives as a prop.

type EpisodeBeat = {
  beat: string;
  spoken?: string;
  display?: string;
  audio_url?: string | null;
  duration_seconds?: number | null;
};

type PresenterClip = {
  beat_index: number;
  beat?: string;
  video_url: string;
  duration_seconds?: number | null;
};

// One slice of one beat, planned by the Episode Director in beia_core.
//
// The shot plan drives the BACKGROUND: what picture is on screen and how it
// moves. The game layer (question, options, countdown, answer) stays beat-driven
// in EpStage, which is how broadcast trivia actually works — the question holds
// while the pictures cut behind it.
//
// Weights, never seconds. The Director cannot know how long a beat runs because
// that comes from the measured mp3; it says only how the beat DIVIDES. A plan in
// absolute seconds would desync the moment the voice came back longer than
// predicted, and a desynced episode plays the answer over the question.
type EpisodeShot = {
  beat_index: number;
  beat: string;
  shot_type: string;
  media_kind: string;
  weight: number;
  motion: string;
  sound_cue?: string | null;
  owns_frame?: boolean;
  //: Filled by the asset step. Absent for renderer graphics, which have no
  //: asset — those shots hold whatever picture was last on screen while the
  //: graphic plays over it.
  media_url?: string | null;
};

type EpisodeSpec = {
  format?: string;
  mechanic?: string;
  pillar?: string;
  difficulty?: string;
  hook?: string;
  question?: string;
  answer?: string;
  payoff?: string;
  choices?: string[];
  correct_index?: number | null;
  correct_order?: number[] | null;
  figures?: { label: string; value: string }[];
  cta_type?: string;
  cta?: string;
  visual_brief?: string;
  image_url?: string | null;
  reveal_image_url?: string | null;
  beats?: EpisodeBeat[];
  avatar_treatment?: string;
  presenter_clips?: PresenterClip[];
  duration_target?: number[];
  //: The shot plan. Absent on older episodes, which fall back to the single
  //: held still — the whole point of keeping that path alive is that a
  //: re-render of an old episode must not break.
  shots?: EpisodeShot[];
};

type BrandIdentity = {
  primary?: string;
  secondary?: string;
  light?: string;
  palette?: string[];
  fonts?: string[];
  tagline?: string;
};

type TriviaEpisodeProps = {
  episode: EpisodeSpec;
  brand?: BrandIdentity;
  brandName?: string;
  accentColor?: string;
  logoUrl?: string;
  siteUrl?: string;
  musicUrl?: string;
  musicVolume?: number;
  narrationUrl?: string; // single fallback track when there is no per-beat audio
};

const EP_FPS = 30;

// Platform chrome, measured against a real Shorts screenshot rather than
// guessed. YouTube puts the back arrow, search and menu across the top and the
// channel handle, description and action rail across the bottom — an episode
// published with the question under the back arrow and the caption colliding
// with the handle. TikTok and Instagram are worse at the bottom, so these are
// sized for the worst case and used everywhere.
const EP_SAFE_TOP = 300;      // ~16% of 1920
const EP_SAFE_BOTTOM = 520;   // ~27% — the action rail and description sit here
const EP_SAFE_SIDE = 96;
// The brand mark and store URL sit in a strip of their own under the safe top.
// Content has to start below it: both used to begin at EP_SAFE_TOP, so a long
// question wrapped straight through "Ruoth" and "ruothstore.com".
// Tall enough to clear a logo (150 wide plus its plate) AND the store URL that
// rides under it. It was 150, which cleared the text-only mark but not a logo.
const EP_HEADER_H = 220;
// The URL sits under whichever mark is above it. At a flat 84 it landed on top
// of the logo, which is why "ruothstore.com" appeared stamped across it.
const EP_SITE_OFFSET_WITH_LOGO = 178;
const EP_SITE_OFFSET_TEXT_ONLY = 84;

// Speech rate measured from real narration takes, used ONLY when a beat has no
// measured audio (the free-voice fallback path). Deliberately a named constant:
// a wrong value here desyncs every beat after it.
const EP_WORDS_PER_SECOND = 2.4;
const EP_MIN_BEAT_SECONDS = 0.9;

const epBeatSeconds = (b: EpisodeBeat): number => {
  if (b.duration_seconds && b.duration_seconds > 0) return b.duration_seconds;
  const words = (b.spoken || b.display || '').trim().split(/\s+/).filter(Boolean).length;
  return Math.max(EP_MIN_BEAT_SECONDS, words / EP_WORDS_PER_SECOND);
};

// Beat index -> [startFrame, endFrame). One source of truth for timing, shared
// by the audio, the stage and the captions so they cannot drift apart.
// The countdown must actually last as long as it says. Narration of "three,
// two, one" takes about 1.5 seconds, so a ring driven purely by speech counted
// 3-2-1 in half the time and gave the viewer no chance to answer — the pressure
// beat is precisely where they are supposed to be deciding.
const EP_MIN_PRESSURE_SECONDS = 3.2;

// Divide each beat's REAL duration among the shots planned for it, by weight.
// Returns one span per shot, in play order. A beat with no shots gets none, and
// the background simply holds — which is the old behaviour, so an episode
// planned without shots still renders.
const epShotTimeline = (
  beats: EpisodeBeat[],
  shots: EpisodeShot[],
  beatSpans: { from: number; to: number }[],
) => {
  const out: { shot: EpisodeShot; from: number; to: number }[] = [];
  for (let i = 0; i < beats.length; i++) {
    const mine = shots.filter((s) => s.beat_index === i);
    if (!mine.length) continue;
    const span = beatSpans[i];
    if (!span) continue;
    const total = mine.reduce((a, s) => a + (s.weight > 0 ? s.weight : 1), 0) || 1;
    let at = span.from;
    mine.forEach((s, k) => {
      const w = s.weight > 0 ? s.weight : 1;
      // The last shot absorbs the rounding, so the shots of a beat always sum
      // to exactly the beat. Rounding each independently left one-frame gaps
      // that flash the layer underneath.
      const to = k === mine.length - 1
        ? span.to
        : Math.min(span.to, at + Math.round(((span.to - span.from) * w) / total));
      out.push({ shot: s, from: at, to: Math.max(at + 1, to) });
      at = to;
    });
  }
  return out;
};

// The motion vocabulary, as the renderer's half of the contract with the
// Director. Every name in `trivia_visual_taxonomy.MOTIONS` must resolve here —
// a Director free to plan motion the renderer silently ignores is exactly the
// failure mode where the pipeline reports success and the video is static.
//
// `t` is progress through the shot, 0..1. Returns a CSS transform plus an
// optional filter.
const epMotion = (
  motion: string, t: number, shotFrames: number,
): { transform: string; filter?: string } => {
  // Moves are specified in ms in the taxonomy; convert once, here.
  const atMs = (ms: number) => Math.min(1, (t * shotFrames) / ((ms / 1000) * EP_FPS));
  const ease = (x: number) => 1 - Math.pow(1 - x, 3);       // ease_out cubic
  const back = (x: number) => 1 + 2.7 * Math.pow(x - 1, 3) + 1.7 * Math.pow(x - 1, 2);

  switch (motion) {
    case 'push_in':
      return { transform: `scale(${1 + 0.10 * t})` };
    case 'pull_out':
      return { transform: `scale(${1.10 - 0.10 * t})` };
    case 'punch_in': {
      const p = ease(atMs(220));
      return { transform: `scale(${1.08 - 0.08 * p})` };
    }
    case 'whip_left': {
      const p = ease(atMs(260));
      return {
        transform: `translateX(${-14 * (1 - p)}%) scale(${1.04 - 0.04 * p})`,
        filter: p < 1 ? `blur(${10 * (1 - p)}px)` : undefined,
      };
    }
    case 'slide_up': {
      const p = ease(atMs(320));
      return { transform: `translateY(${60 * (1 - p)}px)` };
    }
    case 'pop': {
      const p = atMs(260);
      return { transform: `scale(${0.9 + 0.1 * back(p)})` };
    }
    case 'shake': {
      const p = atMs(380);
      const amp = 10 * (1 - p);
      return { transform: `translateX(${Math.sin(p * Math.PI * 6) * amp}px)` };
    }
    case 'pulse': {
      const beat = (t * shotFrames) / (0.6 * EP_FPS);
      return { transform: `scale(${1 + 0.03 * Math.abs(Math.sin(beat * Math.PI))})` };
    }
    case 'glow':
      return { transform: 'scale(1)', filter: `brightness(${1 + 0.25 * (1 - ease(atMs(520)))})` };
    case 'hold':
    case 'cut':
    default:
      return { transform: 'scale(1)' };
  }
};

const epTimeline = (beats: EpisodeBeat[]) => {
  let at = 0;
  return beats.map((b) => {
    let seconds = epBeatSeconds(b);
    if (String(b.beat) === 'pressure') {
      seconds = Math.max(seconds, EP_MIN_PRESSURE_SECONDS);
    }
    const dur = Math.max(1, Math.round(seconds * EP_FPS));
    const span = { from: at, to: at + dur };
    at += dur;
    return span;
  });
};

export const triviaEpisodeFrames = (episode: EpisodeSpec): number => {
  const beats = episode?.beats || [];
  if (!beats.length) return 30 * EP_FPS;
  const spans = epTimeline(beats);
  // A held final frame stops the last word being clipped by the encoder.
  return spans[spans.length - 1].to + Math.round(0.6 * EP_FPS);
};

const EpCaption: React.FC<{
  text: string; accentColor: string; bottom: number; onLight?: boolean;
  bodyFont?: string;
}> = ({ text, accentColor, bottom, onLight = false, bodyFont }) => {
  if (!text) return null;
  return (
    <AbsoluteFill
      style={{
        justifyContent: 'flex-end', alignItems: 'center',
        paddingBottom: bottom, paddingLeft: EP_SAFE_SIDE, paddingRight: EP_SAFE_SIDE,
      }}
    >
      <div
        style={{
          maxWidth: '86%',
          textAlign: 'center',
          fontFamily: bodyFont || 'Arial, Helvetica, sans-serif',
          fontSize: 58,
          fontWeight: 700,
          lineHeight: 1.22,
          color: onLight ? '#111111' : '#FFFFFF',
          textShadow: onLight ? 'none' : '0 4px 18px rgba(0,0,0,0.6)',
          background: onLight ? 'rgba(255,255,255,0.88)' : 'rgba(0,0,0,0.5)',
          borderRadius: 22,
          padding: '16px 28px',
          borderBottom: `6px solid ${accentColor}`,
        }}
      >
        {text}
      </div>
    </AbsoluteFill>
  );
};

// The stage is what the viewer plays on, and it is chosen by MECHANIC rather
// than by format — which is why 18 formats do not need 18 templates.
const EpStage: React.FC<{
  episode: EpisodeSpec;
  phase: string;
  revealed: boolean;
  accentColor: string;
  pressureProgress: number;
  hasStill: boolean;
  onLight: boolean;
  headFont: string;
  bodyFont: string;
  hasPresenter: boolean;
}> = ({ episode, phase, revealed, accentColor, pressureProgress, hasStill, onLight,
        headFont, bodyFont, hasPresenter }) => {
  // The question is the show's voice — it carries the brand's header typeface.
  // Choices and figures are UI and stay on the body face for legibility.
  // The presenter owns his beats outright. He appears on the hook and the
  // reveal and he SAYS both, so every element this component draws -- the
  // question, the options, the countdown, the answer band -- would be words
  // printed over a talking face. The caption is drawn elsewhere and stays,
  // because it sits low over a chest rather than across a face.
  if (hasPresenter) return null;

  const font = bodyFont;
  const ink = onLight ? '#111111' : '#FFFFFF';
  const mechanic = episode.mechanic || 'reveal';
  const choices = episode.choices || [];
  const correct = episode.correct_index;

  // Nothing but the hook is on screen during the hook beat: the first frame is
  // the challenge, and a question header competing with it splits attention.
  // On a visual format the IMAGE is the challenge, so it is already behind this.
  if (phase === 'hook') {
    return (
      <AbsoluteFill
        style={{
          // Centred when the hook is the only thing on screen. With a still
          // behind it the hook moves to the top third, because centring it puts
          // the words directly on the subject — which produced an unreadable
          // first frame of black text on a black silhouette.
          justifyContent: hasStill ? 'flex-start' : 'center',
          alignItems: 'center',
          paddingLeft: EP_SAFE_SIDE,
          paddingRight: EP_SAFE_SIDE,
          paddingTop: EP_SAFE_TOP + EP_HEADER_H,
          paddingBottom: EP_SAFE_BOTTOM,
        }}
      >
        <div
          style={{
            fontFamily: headFont, fontSize: hasStill ? 74 : 92, fontWeight: 700,
            color: ink, textAlign: 'center', lineHeight: 1.15,
            textShadow: onLight ? 'none' : '0 6px 24px rgba(0,0,0,0.5)',
            // A plate behind the words so the hook stays legible whatever the
            // still happens to be behind it.
            ...(hasStill
              ? {
                  background: onLight ? 'rgba(255,255,255,0.9)' : 'rgba(0,0,0,0.55)',
                  borderRadius: 24,
                  padding: '22px 30px',
                }
              : {}),
          }}
        >
          {episode.hook}
        </div>
      </AbsoluteFill>
    );
  }

  const Question = (
    <div
      style={{
        fontFamily: headFont, fontSize: 60, fontWeight: 700, color: ink,
        textAlign: 'center', lineHeight: 1.24, marginBottom: 46,
      }}
    >
      {episode.question}
    </div>
  );

  const Choices = (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 22, width: '100%' }}>
      {choices.map((c, i) => {
        const isRight = revealed && correct === i;
        const isWrong = revealed && correct !== null && correct !== i;
        return (
          <div
            key={i}
            style={{
              fontFamily: font, fontSize: 48, fontWeight: 600,
              color: isWrong ? 'rgba(255,255,255,0.35)' : '#FFFFFF',
              background: isRight ? accentColor : 'rgba(255,255,255,0.10)',
              border: `3px solid ${isRight ? accentColor : 'rgba(255,255,255,0.22)'}`,
              borderRadius: 18, padding: '22px 28px', textAlign: 'left',
            }}
          >
            <span style={{ opacity: 0.6, marginRight: 18 }}>
              {String.fromCharCode(65 + i)}
            </span>
            {c}
          </div>
        );
      })}
    </div>
  );

  const Figures = (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, width: '100%' }}>
      {(episode.figures || []).map((f, i) => (
        <div
          key={i}
          style={{
            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
            fontFamily: font, fontSize: 48, color: '#FFFFFF',
            background: 'rgba(255,255,255,0.08)', borderRadius: 14,
            padding: '18px 26px',
          }}
        >
          <span style={{ opacity: 0.75 }}>{f.label}</span>
          <span style={{ fontWeight: 700 }}>{f.value}</span>
        </div>
      ))}
    </div>
  );

  // When the answer is one of the choices, highlighting it IS the reveal. A
  // banner underneath repeating the same words is noise on a screen that has
  // seconds to land.
  const answerIsAChoice = choices.length > 0 && correct !== null && correct !== undefined;
  const Answer = revealed && !answerIsAChoice ? (
    <div
      style={{
        fontFamily: font, fontSize: 62, fontWeight: 700, color: '#FFFFFF',
        background: accentColor, borderRadius: 20, padding: '26px 32px',
        textAlign: 'center', marginTop: 34,
      }}
    >
      {episode.answer}
    </div>
  ) : null;

  // The countdown is the moment viewers drop, so it has to LOOK like a clock,
  // not a loading bar. A thin progress line under three spoken words read as a
  // buffering indicator; a ticking ring with the number counting 3-2-1 inside it
  // is the visual language every quiz show already taught the audience.
  const secondsLeft = Math.max(1, Math.ceil((1 - pressureProgress) * 3));
  const ringSize = 190;
  const stroke = 14;
  const radius = (ringSize - stroke) / 2;
  const circumference = 2 * Math.PI * radius;
  const Countdown =
    phase === 'pressure' ? (
      <div style={{ display: 'flex', justifyContent: 'center', marginTop: 46 }}>
        <div style={{ position: 'relative', width: ringSize, height: ringSize }}>
          <svg width={ringSize} height={ringSize} style={{ transform: 'rotate(-90deg)' }}>
            <circle
              cx={ringSize / 2} cy={ringSize / 2} r={radius}
              fill="none" stroke={onLight ? 'rgba(0,0,0,0.12)' : 'rgba(255,255,255,0.18)'}
              strokeWidth={stroke}
            />
            <circle
              cx={ringSize / 2} cy={ringSize / 2} r={radius}
              fill="none" stroke={accentColor} strokeWidth={stroke}
              strokeLinecap="round"
              strokeDasharray={circumference}
              strokeDashoffset={circumference * pressureProgress}
            />
          </svg>
          <div
            style={{
              position: 'absolute', inset: 0, display: 'flex',
              alignItems: 'center', justifyContent: 'center',
              fontFamily: headFont, fontSize: 96, fontWeight: 700, color: ink,
              // A small pulse on each tick so the number reads as counting
              // rather than sitting still.
              transform: `scale(${1 + 0.06 * (1 - ((1 - pressureProgress) * 3) % 1)})`,
            }}
          >
            {secondsLeft}
          </div>
        </div>
      </div>
    ) : null;

  let body: React.ReactNode = null;
  if (mechanic === 'choices' || mechanic === 'verdict' || mechanic === 'ordering') {
    body = choices.length ? Choices : null;
  } else if (mechanic === 'calculation') {
    body = Figures;
  }

  // The menu comes down when the answer goes up. An ordering question whose
  // answer is a SEQUENCE rather than one of the options needs its own band, and
  // stacking that under four choices overran the padding and printed the answer
  // straight through the caption -- two lines of text on the same pixels, both
  // unreadable. Once the answer is on screen the options have done their job.
  if (Answer) {
    body = null;
  }

  // With a still behind it the game moves to the top third, so the picture the
  // viewer is being asked to identify is not covered by the question about it.
  return (
    <AbsoluteFill
      style={{
        justifyContent: hasStill ? 'flex-start' : 'center',
        paddingLeft: EP_SAFE_SIDE,
        paddingRight: EP_SAFE_SIDE,
        paddingTop: EP_SAFE_TOP + EP_HEADER_H,
        paddingBottom: EP_SAFE_BOTTOM + 80,
      }}
    >
      {Question}
      {body}
      {Countdown}
      {Answer}
    </AbsoluteFill>
  );
};

const TriviaEpisodeComp: React.FC<TriviaEpisodeProps> = ({
  episode,
  brand = {},
  brandName = 'Ruoth',
  accentColor = '#C0392B',
  logoUrl,
  siteUrl = '',
  musicUrl,
  musicVolume = 0.14,
  narrationUrl,
}) => {
  const frame = useCurrentFrame();
  // Typography and colour come from the BRAND, not from defaults. Every episode
  // before this rendered in a red that is nowhere in Ruoth's palette, set in
  // Arial while the brand specifies Georgia for headers — because the identity
  // document existed and nothing read it.
  const fonts = brand.fonts || [];
  const headFont = `${fonts[1] || 'Georgia'}, Georgia, serif`;
  const bodyFont = `${fonts[0] || 'Arial'}, Arial, Helvetica, sans-serif`;
  const primary = brand.primary || accentColor;
  const light = brand.light || '#F2F2F2';
  const beats = episode?.beats || [];
  const spans = epTimeline(beats);

  // Past the end of the last beat, HOLD the last beat. The composition can run
  // slightly longer than the beats do (audio padding, the pressure floor), and
  // falling back to index 0 there replayed the HOOK -- presenter, hook question
  // and all -- for the final second, after the answer had already been given.
  const foundIndex = spans.findIndex((s) => frame >= s.from && frame < s.to);
  const activeIndex =
    foundIndex >= 0
      ? foundIndex
      : frame >= (spans[spans.length - 1]?.to ?? 0)
      ? Math.max(0, spans.length - 1)
      : 0;
  const active = beats[activeIndex] || {};
  const phase = String(active.beat || 'hook');
  const revealed = beats
    .slice(0, activeIndex + 1)
    .some((b) => ['reveal', 'payoff', 'cta'].includes(String(b.beat)));

  const span = spans[activeIndex] || { from: 0, to: 1 };
  const pressureProgress = (frame - span.from) / Math.max(1, span.to - span.from);

  const presenter = (episode.presenter_clips || []).find(
    (p) => p.beat_index === activeIndex,
  );

  const hasBeatAudio = beats.some((b) => b.audio_url);

  // ── Sound design ──────────────────────────────────────────────────────────
  // Until now the mix was two layers: a music bed and narration. Grepping the
  // whole composition for whoosh, riser, impact, click, ding or sting returned
  // nothing. Professional short-form feels expensive largely because the EAR is
  // rewarded on every state change, and silence between words is the clearest
  // tell that something was assembled rather than edited.
  //
  // These hang off the BEAT spine, which already exists and is driven by the
  // measured narration, so they need no shot plan and cannot drift.
  const sfx = (() => {
    const out: { src: string; from: number; volume: number; duck: boolean }[] = [];
    beats.forEach((b, i) => {
      const at = spans[i]?.from ?? 0;
      const name = String(b.beat || '');
      if (name === 'hook')
        out.push({ src: 'sfx/hook_impact.wav', from: at, volume: 0.55, duck: true });
      if (name === 'reveal')
        out.push({ src: 'sfx/reveal_impact.wav', from: at, volume: 0.6, duck: true });
      if (name === 'payoff')
        out.push({ src: 'sfx/correct_sting.wav', from: at, volume: 0.4, duck: false });
      if (name === 'cta')
        out.push({ src: 'sfx/cta_chime.wav', from: at, volume: 0.35, duck: false });
      if (name === 'pressure') {
        // One tick per second of the countdown, so the pressure beat is heard
        // as well as seen. The ring already animates; this is what makes it
        // feel like time running out rather than a graphic moving.
        const end = spans[i]?.to ?? at;
        for (let f = at; f < end - EP_FPS * 0.3; f += EP_FPS)
          out.push({ src: 'sfx/countdown_tick.wav', from: Math.round(f), volume: 0.3, duck: false });
      }
    });
    return out;
  })();

  // The two cues that must LAND duck the bed under themselves. Without it the
  // impact fights the music instead of punctuating it — the difference between
  // a mix and a pile of simultaneous sounds.
  const duckWindows = sfx.filter((s) => s.duck).map((s) => [s.from, s.from + Math.round(EP_FPS * 0.9)]);
  const musicAt = (f: number) => {
    for (const [a, b] of duckWindows) {
      if (f >= a && f < b) {
        // Fast drop, slow recovery — how a real ducker behaves.
        const t = (f - a) / (b - a);
        return musicVolume * (0.25 + 0.75 * Math.min(1, Math.max(0, (t - 0.25) / 0.75)));
      }
    }
    return musicVolume;
  };

  // ── The shot plan ─────────────────────────────────────────────────────────
  // Where the episode stops being a slideshow. The Director divides each beat
  // into shots; this finds the one on screen now, and holds the last picture
  // through shots that carry no asset (renderer graphics, which play OVER
  // whatever was there rather than replacing it).
  const shotSpans = epShotTimeline(beats, episode.shots || [], spans);
  const activeShotIdx = shotSpans.findIndex((s) => frame >= s.from && frame < s.to);

  // The last shot at or before now that actually carries a picture. Without
  // this, every question card and countdown would black the frame out.
  const pictureShot = (() => {
    if (!shotSpans.length) return null;
    const upto = activeShotIdx >= 0 ? activeShotIdx : shotSpans.length - 1;
    for (let i = upto; i >= 0; i--) {
      if (shotSpans[i].shot.media_url) return shotSpans[i];
    }
    return null;
  })();

  // On a visual format the picture IS the challenge, so it sits behind every
  // beat from frame 0 — the viewer must never wait for the thing they are being
  // asked to identify.
  //
  // A silhouette quiz stays silhouetted until the reveal, then resolves to the
  // real photograph. That is the format's whole payoff, and it is one CSS
  // filter rather than a second generated image.
  const totalFrames = spans.length ? spans[spans.length - 1].to : 1;
  // Two stills, swapped at the reveal. Section 13 asks the screen to change
  // meaningfully every second or two; one image held for the whole episode
  // reads as a slide however slowly it pushes, and the reveal is the beat the
  // episode is built towards — changing the picture there is where the change
  // is worth the most.
  const setupStill = episode.image_url ? resolveMedia(episode.image_url) : undefined;
  const revealStill = episode.reveal_image_url
    ? resolveMedia(episode.reveal_image_url)
    : undefined;
  const still = revealed && revealStill ? revealStill : setupStill;
  const isSilhouette = episode.format === 'silhouette_quiz';
  // The silhouette field is light until the reveal, so white text would vanish
  // into it. Everything else in the composition sits on dark.
  const onLight = Boolean(still) && isSilhouette && !revealed;

  return (
    <AbsoluteFill style={{ backgroundColor: '#0B0B0C' }}>
      {musicUrl ? <Audio src={resolveMedia(musicUrl)!} volume={musicAt} loop /> : null}

      {/* Sound design. Local files, baked into the render image — a remote
          fetch during a render is a single point of failure, and an episode
          that loses its audio bed to a network blip is a failed episode. */}
      {sfx.map((s, i) => (
        <Sequence key={`sfx-${i}`} from={s.from}>
          <Audio src={staticFile(s.src)} volume={s.volume} />
        </Sequence>
      ))}

      {still && isSilhouette ? (
        // A silhouette is an ISOLATED object on a light field, never a
        // full-bleed photo: `cover` plus brightness(0) fills the frame with
        // black and shows the viewer nothing. The still carries a real alpha
        // channel, so blackening it leaves only the shape. At the reveal the
        // filter lifts and the same asset becomes the photograph — which is the
        // whole payoff of the format, from one image.
        <AbsoluteFill style={{ backgroundColor: revealed ? '#0B0B0C' : light }}>
          {/* Sits in the lower two-thirds: the question and captions own the top
              and bottom bands, and the shape must not compete with either. */}
          <AbsoluteFill
            style={{
              justifyContent: 'center', alignItems: 'center',
              paddingTop: 420, paddingBottom: 340, paddingLeft: 80, paddingRight: 80,
            }}
          >
            <Img
              src={still}
              style={{
                maxWidth: '92%', maxHeight: '100%', objectFit: 'contain',
                filter: revealed ? 'none' : 'brightness(0)',
              }}
            />
          </AbsoluteFill>
        </AbsoluteFill>
      ) : pictureShot ? (
        (() => {
          // THE DIRECTED PATH. One picture per shot, each with its own planned
          // motion, cutting every second or two — instead of one still held for
          // thirty-five seconds under a slow linear zoom, which is what every
          // published episode was.
          const { shot, from, to } = pictureShot;
          const shotFrames = Math.max(1, to - from);
          const t = Math.min(1, Math.max(0, (frame - from) / shotFrames));
          const { transform, filter } = epMotion(shot.motion, t, shotFrames);
          const url = resolveMedia(shot.media_url!)!;
          const isVideo = /\.(mp4|mov|webm)(\?|$)/i.test(shot.media_url!);
          const style = {
            width: '100%', height: '100%', objectFit: 'cover' as const,
            transform, filter,
          };
          return (
            <AbsoluteFill>
              {/* Keyed on the shot so a cut is a real cut: without the key,
                  React reuses the element and the browser cross-fades the
                  source swap, which turns every planned cut into a dissolve. */}
              {isVideo
                ? <OffthreadVideo key={`${from}`} src={url} style={style} muted />
                : <Img key={`${from}`} src={url} style={style} />}
              {/* Scrim: captions and choices must stay readable over any photo.
                  Lighter than the old one — the art direction now delivers its
                  own deep shadows, so the heavy gradient that rescued flat
                  `low`-quality images just muddies a graded frame. */}
              <AbsoluteFill
                style={{
                  background:
                    'linear-gradient(to bottom, rgba(0,0,0,0.40) 0%, rgba(0,0,0,0.05) 35%, rgba(0,0,0,0.62) 100%)',
                }}
              />
            </AbsoluteFill>
          );
        })()
      ) : still ? (
        <AbsoluteFill>
          {/* THE LEGACY PATH, kept so re-rendering an older episode that has no
              shot plan still works. A held still reads as a slide, so a slow
              push at least keeps the frame alive. */}
          <Img
            src={still}
            style={{
              width: '100%',
              height: '100%',
              objectFit: 'cover',
              transform: `scale(${interpolate(
                frame,
                [0, Math.max(1, totalFrames)],
                [1, 1.12],
                { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' },
              )})`,
            }}
          />
          <AbsoluteFill
            style={{
              background:
                'linear-gradient(to bottom, rgba(0,0,0,0.55) 0%, rgba(0,0,0,0.15) 35%, rgba(0,0,0,0.75) 100%)',
            }}
          />
        </AbsoluteFill>
      ) : null}

      {/* Per-beat narration, each starting exactly where its beat starts. */}
      {hasBeatAudio
        ? beats.map((b, i) =>
            b.audio_url ? (
              <Sequence key={i} from={spans[i].from} durationInFrames={spans[i].to - spans[i].from}>
                {/* resolveMedia, not the raw URL: CI downloads every asset up
                    front and passes bare filenames, because a fetch that fails
                    mid-render kills an otherwise finished episode. */}
                <Audio src={resolveMedia(b.audio_url)!} />
              </Sequence>
            ) : null,
          )
        : narrationUrl
        ? <Audio src={resolveMedia(narrationUrl)!} />
        : null}

      {/* The presenter is the BACKDROP for its beat, not a panel on top of one.
          HeyGen renders a stock video avatar at the full 1080x1920 already
          standing in this episode's own still, so the clip is the whole picture
          and it covers the frame edge to edge.

          It used to be drawn at its own shape over a dimmed copy of the scene.
          That was written for photo-avatar looks, which come back 16:9 and only
          cover a band. On a full-height video avatar it put HIS copy of the
          still, at a different scale and brightness, on top of the episode's
          copy -- so the clip read as a lit rectangle pasted over the frame and
          the presenter appeared to float. Covering the frame removes the seam;
          there is nothing left to dim, so the scrim is gone too.

          Wrapped in a Sequence so the clip plays from ITS OWN first frame.
          Without it the clip runs on composition time: a reveal presenter a
          couple of hundred frames in was already past the end of its clip, so
          Remotion held the last frame and the avatar stood there staring. */}
      {presenter ? (
        <Sequence from={span.from} layout="none">
          <AbsoluteFill>
            <OffthreadVideo
              src={resolveMedia(presenter.video_url)!}
              style={{ width: '100%', height: '100%', objectFit: 'cover' }}
              muted
            />

            {/* ── Anchoring the presenter in the room ────────────────────────
                HeyGen hands back a finished 1080x1920 frame with the avatar
                already over this episode's still, so we cannot touch the key.
                What we CAN do is everything a compositor does after the key,
                and without it he reads as a cut-out: lit flat and bright
                against a warm, dark, side-lit scene, no shadow under him, and
                nothing in front of him — so he floats rather than stands.

                Four passes, in the order a grade would apply them. All are
                gradients over the finished clip: no extra render cost, no API
                call, and nothing here touches the avatar itself. */}

            {/* 1. LIGHT DIRECTION. The scene is lit from frame left with deep
                   fall-off to the right; the avatar arrives evenly lit. This
                   re-imposes the scene's own key so the two agree. */}
            <AbsoluteFill
              style={{
                background:
                  'linear-gradient(100deg, rgba(255,196,120,0.16) 0%, ' +
                  'rgba(255,170,90,0.05) 34%, rgba(0,0,0,0) 55%, ' +
                  'rgba(0,0,0,0.30) 88%, rgba(0,0,0,0.46) 100%)',
                mixBlendMode: 'soft-light',
              }}
            />

            {/* 2. GRADE. Pulls his whites out of daylight and into the
                   episode's amber, the same shift the stills already carry. */}
            <AbsoluteFill
              style={{
                background: 'rgba(196,116,44,0.14)',
                mixBlendMode: 'color',
              }}
            />

            {/* 2b. HIGHLIGHT RESTRAINT. A white chef's jacket arrives as the
                   brightest object in a frame whose stills are graded for
                   rich blacks and restrained highlights, so he reads as lit
                   by a different production. Multiply pulls only the bright
                   values down and leaves the shadows alone — the whites land
                   in the scene's amber instead of glowing over it. */}
            <AbsoluteFill
              style={{
                background:
                  'linear-gradient(to top, rgba(150,96,44,0.42) 0%, ' +
                  'rgba(168,112,56,0.34) 45%, rgba(190,140,88,0.22) 100%)',
                mixBlendMode: 'multiply',
              }}
            />

            {/* 3. CONTACT SHADOW. A body standing in a room occludes the
                   light reaching the surface it stands on. Without this the
                   eye gets no depth cue at all and reads him as a sticker. */}
            <AbsoluteFill
              style={{
                background:
                  'radial-gradient(120% 42% at 50% 104%, rgba(0,0,0,0.72) 0%, ' +
                  'rgba(0,0,0,0.40) 42%, rgba(0,0,0,0) 72%)',
              }}
            />

            {/* 4. FOREGROUND OCCLUSION — the single strongest "he is in the
                   room" cue. Something out of focus sits between camera and
                   subject, so the frame has depth in front of him as well as
                   behind. Deliberately soft and dark: it must read as a
                   surface the shot is looking over, never as a bar. */}
            <AbsoluteFill
              style={{
                background:
                  'linear-gradient(to top, rgba(18,12,8,0.92) 0%, ' +
                  'rgba(24,16,10,0.78) 5%, rgba(30,20,12,0.34) 11%, ' +
                  'rgba(0,0,0,0) 17%)',
                filter: 'blur(6px)',
              }}
            />

            {/* 5. Optical vignette, matching the 50mm the stills are shot on.
                   Ties his edges into the frame instead of leaving them the
                   brightest thing in it. */}
            <AbsoluteFill
              style={{
                background:
                  'radial-gradient(78% 62% at 50% 42%, rgba(0,0,0,0) 55%, ' +
                  'rgba(0,0,0,0.34) 88%, rgba(0,0,0,0.52) 100%)',
              }}
            />
          </AbsoluteFill>
        </Sequence>
      ) : null}

      {/* When the presenter is on screen the frame is HIS. He is on the hook
          and the reveal only, and on both he is saying the words -- so
          printing them over him is redundant text on a face. Two attempts to
          make that readable (a graded band, then reframing him downward) both
          treated the symptom: the text was still in front of the presenter.
          The question carries the middle beats, where there is no one to
          stand in front of. Captions stay: a caption sits low, over a chest,
          which is where broadcast has always put them. */}
      <EpStage
        episode={episode}
        phase={phase}
        revealed={revealed}
        accentColor={primary}
        pressureProgress={pressureProgress}
        hasStill={Boolean(still)}
        onLight={onLight}
        headFont={headFont}
        bodyFont={bodyFont}
        hasPresenter={Boolean(presenter)}
      />

      {/* The hook beat carries no caption: it is already the whole screen. */}
      {phase === 'hook' ? null : (
        <EpCaption
          text={String(active.display || '')}
          accentColor={primary}
          bottom={EP_SAFE_BOTTOM}
          onLight={onLight}
          bodyFont={bodyFont}
        />
      )}

      {/* Persistent brand mark — present in every frame, selling in none of
          them. Never on the hook beat, where it would cost the first second. */}
      {phase === 'hook' ? null : (
        <AbsoluteFill style={{ justifyContent: 'flex-start', alignItems: 'flex-end', padding: 36, paddingTop: EP_SAFE_TOP }}>
          {logoUrl ? (
            <Img
              src={resolveMedia(logoUrl)!}
              style={{
                width: 150, opacity: 0.95,
                // A dark logo vanishes on the silhouette's light field and a
                // light one vanishes on everything else. A soft plate behind it
                // keeps the mark legible on both without touching the artwork.
                background: onLight ? 'rgba(255,255,255,0.75)' : 'rgba(0,0,0,0.35)',
                borderRadius: 12, padding: 8,
              }}
            />
          ) : (
            <div style={{ fontFamily: headFont, fontSize: 30, color: onLight ? 'rgba(0,0,0,0.55)' : 'rgba(255,255,255,0.7)', fontWeight: 600 }}>
              {brandName}
            </div>
          )}
        </AbsoluteFill>
      )}

      {/* Section 15: the brand stays visually present in EVERY episode, while
          explicit selling stays limited. The site sat under the logo only on
          the CTA beat, so the 15% no-CTA control and every non-product episode
          gave a viewer no way to find the shop at all. It now rides under the
          mark throughout — small, quiet, never covering the game — and steps
          forward only on the CTA beat. */}
      {siteUrl && phase !== 'hook' ? (
        <AbsoluteFill
          style={{
            justifyContent: 'flex-start', alignItems: 'flex-end', padding: 36,
            paddingTop: EP_SAFE_TOP + (logoUrl
              ? EP_SITE_OFFSET_WITH_LOGO
              : EP_SITE_OFFSET_TEXT_ONLY),
          }}
        >
          <div
            style={{
              fontFamily: bodyFont,
              fontSize: phase === 'cta' ? 34 : 24,
              fontWeight: 600,
              letterSpacing: 0.4,
              color: onLight
                ? `rgba(0,0,0,${phase === 'cta' ? 0.8 : 0.5})`
                : `rgba(255,255,255,${phase === 'cta' ? 0.95 : 0.62})`,
              background: phase === 'cta'
                ? (onLight ? 'rgba(255,255,255,0.85)' : 'rgba(0,0,0,0.45)')
                : 'transparent',
              borderRadius: 10,
              padding: phase === 'cta' ? '8px 14px' : 0,
            }}
          >
            {siteUrl}
          </div>
        </AbsoluteFill>
      ) : null}
    </AbsoluteFill>
  );
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
    <Composition
      id="OfferCard"
      component={OfferCard}
      durationInFrames={1}
      fps={30}
      width={1080}
      height={1350}
      defaultProps={{
        headline: 'Your kitchen wall is boring. Here is the fix.',
        subhead: 'Neo-classical kitchen print, ready to hang.',
        price: '£24',
        cta: 'Shop now',
        brandName: 'Ruoth',
        accentColor: '#C0392B',
        background: '#FFFFFF',
        textColor: '#111111',
      }}
    />
    <Composition
      id="HookIntroReel"
      component={HookIntroReel}
      durationInFrames={INTRO_FRAMES + 300}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{
        hook: 'Still guessing this ingredient?',
        videoUrl: '',
        brandName: 'Ruoth',
        accentColor: '#C0392B',
      }}
      calculateMetadata={async ({ props }) => {
        const fps = 30;
        let vidFrames = 300; // 10s fallback if probing fails
        if (props.videoUrl) {
          try {
            const meta = await getVideoMetadata(props.videoUrl);
            vidFrames = Math.round(meta.durationInSeconds * fps);
          } catch (e) {
            // keep fallback — never fail the render on a probe error
          }
        }
        return { durationInFrames: INTRO_FRAMES + Math.max(1, vidFrames), fps };
      }}
    />
    <Composition
      id="HookImageReel"
      component={HookImageReel}
      durationInFrames={INTRO_FRAMES + IMAGE_HOLD_FRAMES}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{
        hook: 'Still guessing this ingredient?',
        imageUrl: '',
        brandName: 'Ruoth',
        accentColor: '#C0392B',
      }}
      calculateMetadata={({ props }) => ({
        durationInFrames:
          INTRO_FRAMES +
          (props.holdSeconds ? Math.round(props.holdSeconds * 30) : IMAGE_HOLD_FRAMES),
        fps: 30,
      })}
    />
    <Composition
      id="TriviaEpisode"
      component={TriviaEpisodeComp}
      durationInFrames={30 * EP_FPS}
      fps={EP_FPS}
      width={1080}
      height={1920}
      defaultProps={{
        episode: {
          mechanic: 'choices',
          hook: 'This dish may not come from where you think.',
          question: 'Where did jollof rice originate?',
          answer: 'Most commonly credited to Senegal',
          choices: ['Nigeria', 'Senegal', 'Ghana'],
          correct_index: 1,
          cta_type: 'follow',
          beats: [
            { beat: 'hook', spoken: 'This dish may not come from where you think.', display: 'Not where you think' },
            { beat: 'challenge', spoken: 'Where did jollof rice originate?', display: 'Where did it start?' },
            { beat: 'clue', spoken: 'The name points to a medieval empire.', display: 'The name is a clue' },
            { beat: 'pressure', spoken: 'Three seconds.', display: 'Three seconds' },
            { beat: 'reveal', spoken: 'Senegal.', display: 'Senegal' },
            { beat: 'payoff', spoken: 'The Wolof of the Senegambia region gave the dish its name.', display: 'Named for the Wolof' },
            { beat: 'cta', spoken: 'Follow for tomorrow.', display: 'Follow for tomorrow' },
          ],
        } as EpisodeSpec,
        brandName: 'Ruoth',
        accentColor: '#C0392B',
        siteUrl: 'ruothstore.com',
      }}
      calculateMetadata={({ props }) => ({
        durationInFrames: triviaEpisodeFrames(props.episode),
        fps: EP_FPS,
      })}
    />
    <Composition
      id="TriviaReel"
      component={TriviaReel}
      durationInFrames={TRIVIA_INTRO_FRAMES + 240 + TRIVIA_OUTRO_FRAMES}
      fps={TRIVIA_FPS}
      width={1080}
      height={1920}
      defaultProps={{
        question: 'True or false: most home-based food businesses undercharge by 25–40%?',
        answer: 'True — and costing it properly is the fix.',
        pillar: 'Business & Costing',
        brandName: 'Ruoth',
        accentColor: '#C0392B',
        siteUrl: 'www.ruothstore.com',
        captions: [] as Caption[],
      }}
      calculateMetadata={({ props }) => {
        const caps = props.captions || [];
        const body = caps.length
          ? Math.round((caps[caps.length - 1].endMs / 1000) * TRIVIA_FPS)
          : 240;
        return {
          durationInFrames: TRIVIA_INTRO_FRAMES + Math.max(1, body) + TRIVIA_OUTRO_FRAMES,
          fps: TRIVIA_FPS,
        };
      }}
    />
    <Composition
      id="QuoteReel"
      component={QuoteVideo}
      durationInFrames={DEFAULT_IMAGES.length * CARD_DURATION}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{ images: DEFAULT_IMAGES, brandName: 'BEIA', accentColor: '#F97316' }}
      calculateMetadata={({ props }) => ({
        durationInFrames: Math.max(1, (props.images?.length || 1) * CARD_DURATION),
      })}
    />
    </>
  );
};
